const sampleDefects = [
    {
        dateCreated: new Date('2025-09-18'),
        apartment: 'EGV',
        roomNumber: 'Lavida-cafe',
        description: 'Vòi xịt WC hỏng',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-09-18'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-19'),
        apartment: 'EGV',
        roomNumber: 'B19-02',
        description: 'Thấm trần WC',
        progress: 'inProgress',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-22'),
        apartment: 'EGV',
        roomNumber: 'B10-09',
        description: 'Máy nước nóng không nóng',
        progress: 'reported',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-22'),
        apartment: 'EGV',
        roomNumber: 'B10-20',
        description: 'Khoá cửa chính không tự khoá',
        progress: 'reported',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-24'),
        apartment: 'EGV',
        roomNumber: 'B23-21',
        description: 'Đèn viền bếp không sáng',
        progress: 'inProgress',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-24'),
        apartment: 'EGV',
        roomNumber: 'B23-21',
        description: 'Máy hút mùi không hoạt động',
        progress: 'completed',
        reason: 'chập nguồn đèn led viền',
        solution: 'Cách li nguồn đèn led viền bếp ra. Máy hút mùi hoạt động bình thường',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-09-24'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-25'),
        apartment: 'EGV',
        roomNumber: 'B31-01',
        description: 'Trào ngược nước từ phiễu thu WC',
        progress: 'completed',
        reason: 'nghẹt đường ống thoát',
        solution: 'thông tắc đường ống thoát',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-09-25'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-09-29'),
        apartment: 'EGV',
        roomNumber: 'A18-08',
        description: 'Đèn phòng ngủ không bật được',
        progress: 'inProgress',
        reason: 'Quạt thông gió bị chập',
        solution: 'tạm thời cách li quạt thông gió. Đèn đã sử dụng bình thường',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-01'),
        apartment: 'EGV',
        roomNumber: 'A20-06',
        description: 'Kệ ti vi bị xệ',
        progress: 'reported',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-01'),
        apartment: 'EGV',
        roomNumber: 'B18-19',
        description: 'Kệ ti vi bị xệ',
        progress: 'reported',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-02'),
        apartment: 'EGV',
        roomNumber: 'A14.11',
        description: 'Máy lạnh đọng nước',
        progress: 'completed',
        reason: 'Máy lạnh bật nhiệt độ thấp + chỉnh chế độ gió yếu',
        solution: 'tăng nhiệt độ và chỉnh chế độ gió về auto',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-02'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-03'),
        apartment: 'EGV',
        roomNumber: 'A18-03',
        description: 'Khung treo rèm bị rớt',
        reason: 'rớt tắc kê giữ khung do rèm bị kéo mạnh xuống',
        solution: 'Lắp lại tắc kê giữ khung',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-04'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-03'),
        apartment: 'EGV',
        roomNumber: 'A18-03',
        description: 'Tay nắm cửa bị lỏng',
        reason: 'lỏng ốc vít giữ tay nắm',
        solution: 'siết chặt ốc vít giữ tay nắm',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-03'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-04'),
        apartment: 'EGV',
        roomNumber: 'A18-03',
        description: 'ống thoát máy giặt bị bể',
        reason: 'hao mòn',
        solution: 'thay ống thoát máy giặt',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-06'),
        cost: 15000,
        remark: 'ống size hơi nhỏ hơn',
    },
    {
        dateCreated: new Date('2025-10-04'),
        apartment: 'EGV',
        roomNumber: 'B21-20',
        description: 'Giường bị nghiêng',
        reason: 'khung giường rớt pát đỡ',
        solution: 'gia cố thêm 2 pát đỡ khung giường',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-06'),
        cost: 8000,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-04'),
        apartment: 'EGV',
        roomNumber: 'B30-20',
        description: 'Máy lạnh chảy nước',
        reason: 'Nghẹt ống nước thoát',
        solution: 'Vệ sinh máy lạnh',
        progress: 'completed',
        priority: 'emergency',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-04'),
        cost: 300000,
        remark: 'Vệ sinh 02 máy lạnh. 150k/máy.',
    },
    {
        dateCreated: new Date('2025-10-06'),
        apartment: 'EGV',
        roomNumber: 'B21-20',
        description: 'Chặn cửa bị rớt',
        reason: 'lắp đặt không có tắt kê giữ',
        solution: 'khoan lại lỗ lắp tắc kê mới',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-06'),
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-06'),
        apartment: 'EGV',
        roomNumber: 'B21-20',
        description: 'Đèn bắt côn trùng không sáng',
        reason: 'hỏng bóng đèn. hư mòn theo thời gian',
        solution: 'đề xuất thay mới bóng đèn',
        progress: 'inProgress',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 160000,
        remark: 'mua 4 bóng',
    },
    {
        dateCreated: new Date('2025-10-06'),
        apartment: 'EGV',
        roomNumber: 'A10-01',
        description: 'Kệ phòng ngủ xệ',
        progress: 'inProgress',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: null,
        cost: 0,
        remark: '',
    },
    {
        dateCreated: new Date('2025-10-07'),
        apartment: 'EGV',
        roomNumber: 'B15-21',
        description: 'Máy giặt không có lỗ xả nước',
        reason: 'chưa cắt lỗ ống thoát ngoài lô gia',
        solution: 'cắt lỗ ống thoát, đấu nối đường ống máy giặt vào',
        progress: 'completed',
        priority: 'normal',
        reportedBy: 'CSKH',
        dateDone: new Date('2025-10-07'),
        cost: 0,
        remark: '',
    },
];
export default sampleDefects;
